[tool.poetry]
name = "classifier-credit-scoring"
version = "0.1.0"
description = ""
authors = ["\"Chadrack mayamba\""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
